### ISSUE TITLE
Open VSX Publishing?

### ISSUE THREAD

**Issue by benbenbenbenbenben** [kavod-io/vscode-jest-test-adapter#109]
Is there a plan to officially publish this extension to Open VSX? 🚀

I have published it (as unverified) in the kavod-io namespace to make it available in gitpod.io IDE - but naturally the namespace is yours to verify etc.

https://open-vsx.org/extension/kavod-io/vscode-jest-test-adapter

https://github.com/eclipse/openvsx/wiki/Namespace-Access

**Comment by rossknudsen** [comment]
Hi @benbenbenbenbenben,

I was aware of the closed nature of VS Code and the marketplace, but wasn't aware of the alternative editors and Open VSX.  I'm happy to publish there as well, is there any coffee change required? Or do I just need a CD pipeline to publish it there too?

**Comment by rossknudsen** [comment]
Added issue to claim ownership

https://github.com/EclipseFdn/open-vsx.org/issues/368

**Comment by benbenbenbenbenben** [comment]
> Hi @benbenbenbenbenben,
> 
> I was aware of the closed nature of VS Code and the marketplace, but wasn't aware of the alternative editors and Open VSX. I'm happy to publish there as well, is there any coffee change required? Or do I just need a CD pipeline to publish it there too?

No changes, just publish with the open vsx CLI.

**Comment by rossknudsen** [comment]
Closing now as this is complete.  The next release should publish in both locations.
