### ISSUE TITLE
Custom config location(s)

### ISSUE THREAD

**Issue by michens** [kavod-io/vscode-jest-test-adapter#110]
**Describe the bug**
We're using React Native and have platform specific config files such as `jest.config.ios.js` which do not get picked up by cosmiconfig, and therefore don't get handled correctly by this extension.

**To Reproduce**
1. Name config file `jest.config.ios.js`
2. Attempt to run tests

**Expected behavior**
There's a way to set one (or more) config locations or cosmiconfig searchPlaces so non-standard configurations can still work

**Screenshots**
N/A

**Link to source**
N/A

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
N/A

**Comment by elsassph** [comment]
We also use a custom configuration location, and without it nothing works.

**Comment by ekzyis** [comment]
Same problem here

**Comment by shazron** [comment]
We need to have external config support for Jest since a lot of us don't put it in package.json

**Comment by jelling** [comment]
Can the config file really only be read from package.json? That would explain some issues I'm seeing but it's not clearly document anywhere that I can find.
