### ISSUE TITLE
console output

### ISSUE THREAD

**Issue by denishowew** [kavod-io/vscode-jest-test-adapter#111]
Thanks for this lovely extension.  How hard would it be to copy `console.log()` output to the Output panel?  Without this I have to switch to running tests in the terminal to see debug output.

**Comment by rossknudsen** [comment]
I presume you're using the test output that was added in a recent release?

**Comment by denishowew** [comment]
Ah, thanks, I hadn't noticed the drop-down menu on the Output window, selecting "Jest" there did the trick.

**Comment by rossknudsen** [comment]
Yeah I released that without much fanfare. So I'm not surprised you didn't know about it.

**Comment by denishowew** [comment]
I've just noticed that it's clearly explained in the Readme.  <:-|

Thanks again for a great (well documented) extension.
