### ISSUE TITLE
Error loading tests when there are jest options in the package.json

### ISSUE THREAD

**Issue by 2N5** [kavod-io/vscode-jest-test-adapter#113]
I have the simplest react project that uses create-react-app,
![image](https://user-images.githubusercontent.com/25265599/109321619-0cad3600-785a-11eb-952e-b1b038c6f2ab.png)

if there is no configuration in the package.json, all tests are displayed correctly
![image](https://user-images.githubusercontent.com/25265599/109322035-7dece900-785a-11eb-92a2-f710d1aa6e09.png)

but if you add settings for the jest field to the package.json, then an error appears in loading tests
![image](https://user-images.githubusercontent.com/25265599/109321276-a0cacd80-7859-11eb-93f7-1e749a87d536.png)

**Desktop:**
 - OS: Windows

**Comment by rossknudsen** [comment]
Can you copy the full output from the console?  Or at least the top part that is saying what the bad config is?  Don't need the full list of best command options.

**Comment by 2N5** [comment]
![image](https://user-images.githubusercontent.com/25265599/109414249-a2f86d80-79ba-11eb-831e-fdb7e75aedd1.png)

Here is a screenshot of the top of the error, but it is not informative at all.
Have you tried to reproduce my error?
I meet it on every project if I use the jest configuration in package.json

**Comment by 2N5** [comment]
So, any updates?

**Comment by 2N5** [comment]
@rossknudsen, I realized that if the config jest is somehow changed from the default config, then the tests are not loaded. and it doesn't matter if this change is in the package.json or in the jest.config.json file

**Comment by PawelJ-PL** [comment]
I can see the same problem
