### ISSUE TITLE
Cannot find ts-node dependency

### ISSUE THREAD

**Issue by RafaelRodriguesFraga** [kavod-io/vscode-jest-test-adapter#116]
**Describe the bug**

So, I'm using Jest to make my tests and the first error was "jest is not recognized as an internal or external command". So I installed jest globally with "npm install -g jest".  But another error just appeared. It's in the image below. ts-node is installed on package.json. I really don't know what to do anymore. Can someone help me? 

If I go in the terminal and just tap "yarn test" the test is working. But I want to use the extension. Another question: There's another way to fix this without installing things globally? I learned this is a bad practice. If it is, why? And why the hell the extension is using global dependecies?

**To Reproduce**
1. Install the extension
2. Get Error

**Expected behavior**
Tests to appear and work.

**Screenshots**

**1.  Error**

![image](https://user-images.githubusercontent.com/29709111/113468400-4efb0180-941c-11eb-871e-d9ce5667680d.png)

**2.  jest.config,ts**

![image](https://user-images.githubusercontent.com/29709111/113468447-a8fbc700-941c-11eb-9001-fd2d1d016969.png)

**3.  Dependencies from package.json**

![image](https://user-images.githubusercontent.com/29709111/113468538-19a2e380-941d-11eb-93ab-f44165bb61e5.png)

**4.  tsconfig.json (if needed)**

![image](https://user-images.githubusercontent.com/29709111/113468557-317a6780-941d-11eb-9f34-1153c94e04d3.png)

**Comment by RafaelRodriguesFraga** [comment]
Worked installing ts-node globally but I still want to know if this is a bad practice

**Comment by rossknudsen** [comment]
Yeah, you probably don't want those installed globally, as different projects will want different versions.

**Comment by RafaelRodriguesFraga** [comment]
But If I don't  do this, it'll not work. It'll be back to the errors
