### ISSUE TITLE
Cannot run tests from sidebar, whithout `name`-field in package.json

### ISSUE THREAD

**Issue by lmeysel** [kavod-io/vscode-jest-test-adapter#117]
**Describe the bug**
- [ ] test load missing suites/tests
- [ ] test load errors
- [x] test running errors

**To Reproduce**
1. Setup a project to be tested with jest
1. Make sure in package.json is no `name` field
2. Restart VSCode
3. Run test from sidebar sidebar (not codelens!)

**Expected behavior**
Test should run normally, but they don't. Without the `name`-field in package.json, jests logpanel shows
```
[INFO] Running Jest tests... ["undefined ....]
```
I stumbled across this, when testing my JS in a laravel-application, where the package.json manages the dependencies but is not meant to be published, thus, the `name`-field was missing.

**Desktop:**
 - OS: Windows

**Additional context**

**Comment by rori4** [comment]
wow I was browsing the issues here and this actually solved my issue why tests were not running :D

**Comment by grabofus** [comment]
Same issue for me working in a monorepo, I've jumped through the source code and the issue seem to originate from [here](https://github.com/kavod-io/vscode-jest-test-adapter/blob/abe458db6016848372807813699a1cb6afe3f839/src/adapter.ts#L199) and [here](https://github.com/kavod-io/vscode-jest-test-adapter/blob/abe458db6016848372807813699a1cb6afe3f839/src/adapter.ts#L201).

In both places (at `t.projectId === project.id`) `undefined` is compared with `"undefined"` which leads to no tests being run. Modifying to code to `t.projectId ?? 'undefined' === e.id` seem to resolve to issue.
