### ISSUE TITLE
Jest Command Line

### ISSUE THREAD

**Issue by J4CKVVH173** [kavod-io/vscode-jest-test-adapter#135]
I use custom [craco](https://github.com/gsoft-inc/craco) config in my project. And I could not find any ways to run test via `yarn test`. The extension runs tests directly through jest and my custom extensions for project do not work.

Is there any way to specify the launch of tests via `yarn test` or `npm start test` ?

**Comment by lgiancol** [comment]
I would like this too. I need to be able to run `npm run test --` in order to have my tests run properly.

**Comment by charles-allen** [comment]
If this is possible, I believe it would also be a solution to #93
