### ISSUE TITLE
Yarn 2 - PNP - can't find Jest

### ISSUE THREAD

**Issue by GitProdEnv** [kavod-io/vscode-jest-test-adapter#138]
This is a great extension and my favorite one.

But if I run with Yarn 2 - Plug and Play, it can't find Jest, since yarn 2 has no node_modules/.bin executable. 

So switching from NPM to Yarn 2 is a really big issue. :(((

I tried to add in extension settings the path such as `yarn jest` but it didn't work. The path resolves to my user's dir
`../../../../home/{user}/yarn` and just appends `yarn` to the path.

Any help greatly appreciated!!! I still want to use this extension :+1:

**Comment by nikolaev-k** [comment]
Might be too late, but you can run `which yarn`, it will output something like `/usr/local/bin/yarn`. After this you can set the `"jestTestExplorer.pathToJest": "/usr/local/bin/yarn jest"`.
