### ISSUE TITLE
Tests not running but visible in the explorer list

### ISSUE THREAD

**Issue by norcino** [kavod-io/vscode-jest-test-adapter#147]
On the testing window i am able to view all the tests listed in this way:
> src
 > Accordion
 ....

When I try to run the tests, all, individually, from the code or from the list, I see the icon (stop) tuning briefly blue with a play symbol to turn then back gray (stop).

From the output: Jest(@my/componentname), I can see the following:
> Running tests for '@my/componentname'

> @my/componentname@1.0.5 test
> react-scripts test --env=jsdom "--testLocationInResults" "--json" "--useStderr" "--outputFile" > "C:\\Users\\me\\AppData\\Local\\Temp\\jest_runner_.json" "--testNamePattern" "^renders Accordion component with single item$" "c:\\\\some\\\\path\\\\src\\\\Accordion\\\\Accordion\\.test\\.js"

> No tests found, exiting with code 1
> Run with `--passWithNoTests` to exit with code 0
> In C:\some\path
>  120 files checked.
>  testMatch: C:/some/path/src/**/__tests__/**/*.{js,jsx,ts,tsx}, C:/some/path/src/**/*.{spec,test}.{js,jsx,ts,tsx} - 22 matches
>  testPathIgnorePatterns: \\node_modules\\ - 120 matches
>  testRegex:  - 0 matches
> Pattern: c:\\\\some\\\\path\\\\src\\\\Accordion\\\\Accordion\\.test\\.js - 0 matches

My file is located here
_"C:\some\path\src\Accordion\Accordion.test.js"_
The workspace root is located here
_"C:\some\path"_
The node_module .bin folder contains jest as required.

What am i doing wrong?
Why I can see the filename being broken from Accordion.test.js to Accordion\\.test\\.js?

**Comment by mrburrito** [comment]
I'm having the exact same problem. It seemed to be working for me last week, but this morning I get the behavior above. I can see all my tests in the explorer and click the run/debug buttons there. I can click Run or Debug in the editor view above a test. When I do, the icon goes blue as though running then immediately back to gray.

VSCode 1.72.0
vscode-jest-test-adapter 0.8.1

**Comment by Impactorian** [comment]
Just started using this test explorer and got the same behaviour here...
What I recognized now is that is running normal till at least 1 one test expectations fails. Then all get back to gray instead showing which one is red...
Very annoying to find out which one it is becaus you have to run every single test manually to see which one is now failing...

VSCode 1.72.2
vscode-jest-test-adapter 0.8.1
