### ISSUE TITLE
Please consider removing test explorer UI from the dependencies and start consuming VSCode native API 

### ISSUE THREAD

**Issue by abhijit-chikane** [kavod-io/vscode-jest-test-adapter#152]
![image](https://github.com/kavod-io/vscode-jest-test-adapter/assets/50770619/84490e2a-f04c-48f0-aeee-de12ea5ead79)
![image](https://github.com/kavod-io/vscode-jest-test-adapter/assets/50770619/baef1e1c-ded9-420c-8b3e-0f75aefe3602)

**Comment by SquirrelsMcGee** [comment]
It appears that this repo has not been maintained in quite a while and thus is unlikely to get more features, unfortunately.

I've started some work on this as a personal challenge but no promises as to whether or not I'll be able to get it up and running, if anyone else wants to contribute feel free to message

**Comment by rossknudsen** [comment]
I was planning on making improvements (there is an open feature branch).  But I found that the existing [Jest extension](https://marketplace.visualstudio.com/items?itemName=Orta.vscode-jest) has all the features that this extension has.  If you find that it does not support your project structure, I suggest you put the effort into updating that extension instead.
