### ISSUE TITLE
Release it to the marketplace

### ISSUE THREAD

**Issue by SSmale** [kavod-io/vscode-jest-test-adapter#24]
Please release this to the maker place as the fork has now been removed

- [x] Add the release url to the Test explorer project
- [ ] add steps to your readme for the VSIX installation method until the release to the marketplace

**Comment by rossknudsen** [comment]
Hi @SSmale, thanks for the confidence!  Since Covid19 hit, I've been a bit demoralised, otherwise I might have released sooner.

Anyway, I've published a Preview version of the extension to the marketplace.  Feel free to submit bugs/feature requests as you see fit.
