### ISSUE TITLE
Test Explorer doesn't discover any tests

### ISSUE THREAD

**Issue by KaiRoesner** [kavod-io/vscode-jest-test-adapter#30]
I just installed the version 0.3.0 Jest Test Explorer and the version 2.18.0 Test Explorer UI extensions but the Test Explorer UI does not discover any tests. Also I don't get any error log. I have the following project setup:
- `package.json` (showing only jest stuff):
```json
{
    "name": "foo",
    "description": "bar",
    "version": "0.0.1",
    "scripts": {
        "test": "jest --runInBand"
    },
    "devDependencies": {
        "jest": "=23.2.0",
        "jest-cli": "=23.2.0",
        "jest-junit": "=3.7.0"
    }
}
```
- `jest.config.js` at project root level:
```javascript
module.exports = {
    verbose: true,
    collectCoverage: false,
    testRegex: "\./test/.*_test\.js$",
    testPathIgnorePatterns: [ "/node_modules/" ],
    moduleFileExtensions: [
      "js",
      "json"
    ]
}
```
- jest at `./node_modules/.bin/jest`
- `.vscode/launch.json` settings:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Jest: All",
            "type": "node",
            "request": "launch",
            "program": "${workspaceFolder}/node_modules/.bin/jest",
            "args": ["--runInBand"],
            "console": "integratedTerminal",
            "internalConsoleOptions": "neverOpen",
            "windows": {
              "program": "${workspaceFolder}/node_modules/jest/bin/jest",
            }
        },
        {
            "name": "Jest: Current File",
            "type": "node",
            "request": "launch",
            "program": "${workspaceFolder}/node_modules/.bin/jest",
            "args": ["--runInBand", "${fileBasenameNoExtension}"],
            "console": "integratedTerminal",
            "internalConsoleOptions": "neverOpen",
            "windows": {
              "program": "${workspaceFolder}/node_modules/jest/bin/jest",
            }
        }        
    ]
}
```
- tests folder at `./test` with test files named `*_test.js` in subfolders thereof

Doing `npm run test` in a terminal works fine, i.e. runs all my tests. Ditto when doing `RUN Jest: All` or pressing `F5` in VSCode.

**Comment by rossknudsen** [comment]
One real quick thing that sticks out is the version of Jest.  A quick test would be to see if you bump to the latest version whether that makes any difference.  I'm not sure it will make a difference though - finding the tests doesn't use Jest itself...

If you set the `jestTestExplorer.logfile` setting to a valid text file, you should see any errors in the log.  Getting no errors may indicate that it is not finding the Jest config or something.

**Comment by KaiRoesner** [comment]
Thanks for the quick reply! I upgraded jest to 25.3.0 and that unexpectedly did the trick... hm. Now, I'm having a different issue: When running all tests some fail (although they do not when running them via npm) and when I re-run the failed tests separately they pass. Might be due to my code and tests being heavily asynchronous... Bus as I said, that's a different issue so I close this one.

**Comment by rossknudsen** [comment]
Well, I'm not advocating that a newer version of Jest is the solution to your problem.  But thank you for identifying that.  Its a bit of a head-scratcher why that would make a difference.

One other thing regarding why some of your tests fail when running multiple at once may be because the test settings that are passed to the test runner may be different to what is passed at runtime.  Although what you have posted above is fairly simple.

Oh, I just noticed that you pass the `--runInBand` option in your package.json.  That runs the tests serially, rather than in parallel.  This extension doesn't look at the scripts in package.json.  If your tests require that flag, then that is likely to be the problem.  You might be able to specify it in the `jest.config.js` file, perhaps `maxConcurrency` will do what you want.

**Comment by rbuckton** [comment]
I am noticing the same issue with Jest Test Explorer 0.3.3 and Jest 24.8.0. I tried debugging vscode-jest-test-adapter and found that micromatch isn't matching 'c:/path/to/file.test.ts' against the pattern 'C:/path/to/**/*.test.ts', despite the fact that DOS/Windows drive letters are case insensitive (i.e. `c:` and `C:` are synonymous):

![image](https://user-images.githubusercontent.com/3902892/80653731-a4ba7300-8a2f-11ea-8590-183f6279aff7.png)

It looks like you might want to try passing `{ nocase: process.platform === 'win32' }` to `mm.any` to avoid the case sensitivity issue on Windows.

**Comment by rossknudsen** [comment]
Thanks @rbuckton.  I've taken your advice and included the nocase flag and added some unit tests (not testing all permutations, but can be expanded).  Open a ticket if 0.3.4 doesn't fix the issue for you.  

Also, did you download the source to debug, or use the source maps in the extension?  Just interested.
