### ISSUE TITLE
Support space character in project path

### ISSUE THREAD

**Issue by zzzorgo** [kavod-io/vscode-jest-test-adapter#42]
I encountered an issue where having space character in my project folder name prevented plugin from presenting test lists. Basicly it became unusable. May be plugin needs more explicit error message in the UI (there was none) or support such pathes

OS: Win 10

**Comment by rossknudsen** [comment]
Hi @zzzorgo, thanks for reporting this.  It seems like a problem in a dependency.  I have raised there:

jest-community/jest-editor-support#41.

**Comment by rossknudsen** [comment]
Decided that I could deal with the problem in this codebase rather than the third-party dependency.  So hopefully this is working for you now.  I'll close this issue, but if you find that there is still a problem, feel free to reopen.
