### ISSUE TITLE
Concatenation in test case description causes test loading fail

### ISSUE THREAD

**Issue by zzzorgo** [kavod-io/vscode-jest-test-adapter#43]
If you add description to your `it` test-case as two concatenated string via `+` operator test loading failes.

Minimal repository: https://github.com/zzzorgo/vscode-jest-test-adapter-issue
There is repo with two issues i was just too lazy to create separate repos, look for concatenatedDescription.test.js file

**Comment by rossknudsen** [comment]
For completeness - this seems to be an issue in the parser in `jest-editor-support`.  There is an open PR to update the parser (jest-community/jest-editor-support#30) which may fix this.
