### ISSUE TITLE
Using function as module factory in jest.mock causes test loading fail

### ISSUE THREAD

**Issue by zzzorgo** [kavod-io/vscode-jest-test-adapter#44]
If you use function instead of object as module factory in jest.mock call your test will not load. Jest documentation doesn't tell anything about validity of this syntax but nevertheless jest runner works with it https://jestjs.io/docs/en/jest-object#jestmockmodulename-factory-options.

Minimal repository: https://github.com/zzzorgo/vscode-jest-test-adapter-issue
There is repo with two issues i was just too lazy to create separate repos, look for jestMockWithFunction.test.js file

**Comment by rossknudsen** [comment]
For completeness - this seems to be an issue in the parser in `jest-editor-support`.  There is an open PR to update the parser (jest-community/jest-editor-support#30) which may fix this.
