### ISSUE TITLE
Ignore error in single test file loading when loading all tests and report it to user

### ISSUE THREAD

**Issue by zzzorgo** [kavod-io/vscode-jest-test-adapter#45]
Now if you have some invalid test files like in this repo https://github.com/zzzorgo/vscode-jest-test-adapter-issue, test loading fails and you unable to run even valid ones using UI. One test disallows to run all tests. I think it would be better to ignore errors while loading this tests and show in the UI that this files are invalid. 

Motivation: When I've just started using plugin I had two invalid files but had no idea about it. Only couple of hours with modified plugin code and extensive logging helped me find issues.

**Comment by rossknudsen** [comment]
The PR I've raised covers a lot of what you want, but details of what the issues are with any given test are not ideal - you'll have to go check the logs to find out.  I've raise an issue with the host adapter to address this (hbenl/vscode-test-explorer#130).

**Comment by rossknudsen** [comment]
I've merged the PR.  Please let me know if it solves your issue.  Unfortunately it won't make your tests work.  I'll address them in the other issues that you've raised.

**Comment by zzzorgo** [comment]
Thank you! My problem was solved by editing tests themselves (only two) so the purpose of this issues is two make a better experience for other not so committed users :)

**Comment by rossknudsen** [comment]
Cool, I'll close this now.  If in error, please reopen.
