### ISSUE TITLE
Support dynamically generated tests

### ISSUE THREAD

**Issue by rbuckton** [kavod-io/vscode-jest-test-adapter#48]
The adapter doesn't seem to support tests that were generated dynamically. For example, I have a test file whose tests are generated from a `.json` file containing test scenarios (from the commonmark spec). The Test Explorer shows the file was discovered, but I am unable to see any results from the tests:

![image](https://user-images.githubusercontent.com/3902892/80655017-85711500-8a32-11ea-9b8a-13ea2665a713.png)

**Comment by rossknudsen** [comment]
I assume that the generated files are actually create on disk.  If that isn't the case, let me know.

Also, are you running all the tests at once, or just running specific ones?

Looking at your screenshot, it appears that the test file was found, but no tests were found in that file.  There are some limitations of the parser, which will hopefully be addressed soon (checkout the jest-editor-support package).  You might find more information in the logs about the parsing of the tests and if the parsing actually resulted in an error, then the latest version of the extension should have visual feedback as well.

If you can show a sanitised sample of the generated test, then I might be able to spot an issue, or debug it locally.

**Comment by rbuckton** [comment]
I looked into this a bit and I believe this is a limitation of the `jest-editor-support` package that you depend on, as it actually parses the test file and looks for calls to `describe`, `it`, and other similar functions. This won't work for dynamically generated tests like the ones in my case, as it requires runtime evaluation:

https://github.com/rbuckton/tsdoc/blob/6726d44fb4cce79a82fa4c3d30e0e7317e5c9b6b/tsdoc/src/beta/parser/__tests__/commonmark/spec.test.ts#L41-L59
```ts
for (const [section, tests] of groupBySection(allTests)) {
    (onlySections.has(section) ? describe.only :
        (skipAll || skipSections.has(section)) ? describe.skip :
        describe)(section, () => {
        for (const test of tests) {
            (onlyExamples.has(test.example) ? it.only :
                skipExamples.has(test.example) ? it.skip :
                it)(`<https://spec.commonmark.org/0.29/#example-${test.example}>`, () => {
                const parser: BlockParser = new BlockParser(test.markdown);
                const document: Document = parser.parse();
                const emitter: HtmlEmitter = new HtmlEmitter();
                emitter.emit(document);
                const actual: string = emitter.toString();
                expect(actual).toBe(test.html);
                expect(document).toMatchSnapshot();
            });
        }
    });
}
```

I've instead switched to generating the entire test file as part of a pre-build step, which allows `jest-editor-support` discovery to work.

While you can probably close this issue as something unactionable, if you do want to consider a blanket workaround one option might be to still try to run tests in a file where tests aren't discovered and report results in some fashion (possibly just on the file itself).

**Comment by rossknudsen** [comment]
Thanks for the example code - I see what you mean by generated now.

There are some significant things to overcome for this to work, which I'll have to think through.  But there are a number of other issues where the parser isn't able to identify the tests, but the test results will be available when the tests are run.  The issue is, since I can't allocate the test results to a discovered test, they are just swallowed.  As I mentioned, there are a couple of open issues to do with the parser failing to interpret a test file.  The test results would be present in those cases too, but then can't be associated to a parsed file.
