### ISSUE TITLE
Add tests discovered at runtime to test hierarchy

### ISSUE THREAD

**Issue by rossknudsen** [kavod-io/vscode-jest-test-adapter#53]
Some tests cannot be discovered at parse time.  This could be due to limitations of the parser or because the tests are produced dynamically as the test file executes.  The host extension allows us to add suites and tests at test execution time by including them in the suite event.

It may be challenging to handle the ids, labels and line numbers for these tests.

Affects #48 #44 and #43

**Comment by patroza** [comment]
This would be great. we're trying to use the test explorer with matechs effects Jest test framework;
https://github.com/Matechs-Garage/matechs-effect/blob/master/packages/test-jest/test/root.test.ts

which doesn't define the usual describe/it/test in the test files. Wallaby picks up on them, but not the test adapter.
