### ISSUE TITLE
Correctly parse jest config

### ISSUE THREAD

**Issue by tobilen** [kavod-io/vscode-jest-test-adapter#55]
Parsing of jest configurations is very limited to the point that it is not usable in most projects i work in. This is mainly due to two issues.

Current implementation:
https://github.com/kavod-io/vscode-jest-test-adapter/blob/a470a2c6772e48aa3b28cd75e3a47ab1ea03f5a4/src/repo/repoHelpers.ts#L31-L46

1. It expects a json parsable object in `jest.config.js`. This _can_ (and in most cases *is*) actually a module, i.e.
```js
const fs = require('fs');
const { rootDir, ...filteredConfig } = require('./setup/jestConfig');

const projects = fs
  .readdirSync('packages')
  .filter((folder) => folder[0] !== '.')
  .map((folderName) => {
    try {
      fs.accessSync(`packages/${folderName}/jest.config.js`);
      return `<rootDir>/packages/${folderName}`;
    } catch (e) {
      return {
        ...filteredConfig,
        displayName: folderName,
        testRegex: `packages/${folderName}.*(Test|.test)\\.(t|j)sx?$`,
      };
    }
  });

module.exports = {
  ...filteredConfig,
  roots: ['<rootDir>'],
  projects,
};
```

2. It only takes the *first* setup file, when most larger jest configs have multiple, i.e.
```js
module.exports = {
  testRunner: 'jest-circus/runner',
  clearMocks: true,
  roots: ['<rootDir>'],
  snapshotSerializers: ['jest-date-serializer', 'enzyme-to-json/serializer'],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  testEnvironment: 'jest-environment-jsdom-sixteen',
  setupFilesAfterEnv: [
    'jest-canvas-mock',
    'jest-localstorage-mock',
    '<rootDir>/setup/index.ts',
  ],
  rootDir: '<rootDir>/../../../',
};
```

**Comment by rossknudsen** [comment]
Hey thanks for pointing out the faulty implementation. Probably the easiest way to deal with it is to remove the code. I'm pretty sure that the setup files are not used.

**Comment by tobilen** [comment]
thanks for the hint. i'll try to find some time this week to try that

**Comment by rossknudsen** [comment]
Sorry, I want meaning for you to change anything. I just need to remove the need for the setup files since they're not used.

**Comment by tobilen** [comment]
just as confirmation: everything is now working as expected :heart_eyes: 

thanks for the quick fix
