### ISSUE TITLE
Error when package.json is in subfolder

### ISSUE THREAD

**Issue by awesomeunleashed** [kavod-io/vscode-jest-test-adapter#56]
When opening a workspace folder that has the package.json in a subfolder (instead of at the root), the test explorer says "Error while loading tests - click to show." Clicking on that message gives this output:
```
[Error: ENOENT: no such file or directory, open '<workspace-folder>/package.json'] {
  errno: [33m-2[39m,
  code: [32m'ENOENT'[39m,
  syscall: [32m'open'[39m,
  path: [32m'<workspace-folder>/package.json'[39m
}
```

A workaround is to use a multi-root workspace with a setup like this:
```
{
	"folders": [
		{
			"path": "../<package.json folder>"
		},
		{
			"path": ".."
		}
	],
	"settings": {
		"files.exclude": {
			"<package.json folder>": true
		}
	}
}
```
...but that ends up with a little bit of a strange workspace structure, and it still shows the error (along with the tests).

**Comment by rossknudsen** [comment]
Cool, I found the issue - a silly bug.
