### ISSUE TITLE
Error trying to discover tests"[32m'/bin/sh: ../../../../node_modules/jest/bin/jest.js: No such file or directory\n'[39m"

### ISSUE THREAD

**Issue by somewhatabstract** [kavod-io/vscode-jest-test-adapter#60]
I think something may be off with the working directory as I get this error in our project. I have tried explicitly setting the path to jest and to the config (though both are standard locations) and still get the same error.

```shell
[32m'/bin/sh: ../../../../node_modules/jest/bin/jest.js: No such file or directory\n'[39m
```

**Comment by rossknudsen** [comment]
With four levels of hierarchy (`../../../../`) are you using a monorepo framework or something?  Explicit handling of your project setup might be required.  If its OSS, point me in the right direction.

**Comment by somewhatabstract** [comment]
That's just it, the root level of the project is not four levels up. That `node_modules` folder is at the root, so I don't know why it is trying to move four folders up.

**Comment by somewhatabstract** [comment]
Sadly, this project isn't OSS, but I will try to reproduce on one that is.

Something to know is that the root level `jest.config.js` is a symlink to a file in a folder that is like `config/jest/jest.config.js`.

**Comment by rossknudsen** [comment]
You should be able to remove everything except the package.json and jest configuration and replace your test files with a single dummy test.  But it is the relative location of the the files that matters.

Can you also check you're on v0.5.1 as well.
