### ISSUE TITLE
Unable to use extension

### ISSUE THREAD

**Issue by ivanji** [kavod-io/vscode-jest-test-adapter#61]
Hi - thanks for creating this but I'm unable to use it in my projects. I'm running a NextJS project with the Jest configuration found below but the extension shows all my tests with a red warning sign and the errors for all of them is the following:

```Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
```

Jest config within package.json :

```
"jest": {
    "moduleDirectories": [
      "node_modules",
      "src"
    ],
    "testPathIgnorePatterns": [
      "<rootDir>/.storybook/",
      "<rootDir>/.next/",
      "<rootDir>/node_modules/"
    ],
    "transform": {
      "^.+\\.jsx$": "babel-jest",
      "^.+\\.js$": "babel-jest"
    },
    "moduleNameMapper": {
      "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/__mocks__/fileMock.js",
      "\\.(css|less|sass|scss)$": "identity-obj-proxy"
    },
    "collectCoverage": true
  },
```

Babel config:

```
{
  "presets": ["next/babel"]
}

**Comment by rossknudsen** [comment]
Hey, sorry to hear that you are having issues.  Can you confirm something for me?  I suspect that your package.json is not in the root of the vscode workspace.  This means that the extension is not able to find the package.json file and see the Jest config.  Let me know - otherwise something else is going on.

I haven't used NextJS yet, and specific support might need to be added (currently there is explicit support for Create React App and Nx.dev).

**Comment by ivanji** [comment]
Thanks. package.json is at the root of the project. After seeing your message I just decided to reinstall the extension. Given that I had disabled other Jest related extensions and this time it worked! Thanks.
