### ISSUE TITLE
Wrongly treating jest.config.js as JSON

### ISSUE THREAD

**Issue by IGx89** [kavod-io/vscode-jest-test-adapter#64]
Hello! First, really appreciate you bring this extension back from the grave!

Second, it appears that your extension is attempting to parse my jest.config.js as JSON instead of evaluating it as JavaScript. For example, when I have a very basic config like so:

```
module.exports = {
	clearMocks: true,
	collectCoverage: true
};
```

I get the following error:

```
[2020-05-21 20:43:13.960] [ERROR] Error trying to parse Jest setup file: c:\Development\myaccount-frontend\jest.config.js [SyntaxError: Unexpected token m in JSON at position 0
	at JSON.parse (<anonymous>)
	at c:\Users\XXX\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.3.3\dist\extension.js:425:2523169
	at Generator.next (<anonymous>)
	at o (c:\Users\XXX\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.3.3\dist\extension.js:16:1418)]
```

Is this a bug, or is there something I need to do myself to get it to recognize that it's a JS file and not a JSON file?

Thanks!

**Comment by rossknudsen** [comment]
Can you tell me what version of the extension you have?  There was an issue around that kind of behaviour that was recently fixed.  I'm interested in whether the auto-updating is working correctly.

**Comment by IGx89** [comment]
Sure! 0.3.3. VS Code believes it’s the latest and the Marketplace on the web believes 0.2.0 is the latest 🤷🏼‍♂️

**Comment by rossknudsen** [comment]
Ok cool. Do you want to try uninstalling and reinstalling? That should bring you to the latest version. I know there is an issue with the marketplace version. You've just confirmed that it is now a significant issue.

**Comment by IGx89** [comment]
After uninstalling and re-installing it now shows v0.2.0 installed! At least that matches the Marketplace version now. Surprisingly my issue went away however, everything's working now. Don't know if that helps you or not.

**Comment by rossknudsen** [comment]
Cheers. I have released a patch version that gets everything in sync as a temporary fix. I have to update the CI pipeline to fix permanently. Closing this for now, please reopen if problem persists.
