### ISSUE TITLE
Error while loading tests on Windows WSL

### ISSUE THREAD

**Issue by peterjuras** [kavod-io/vscode-jest-test-adapter#65]
**Describe the bug**
- [x] test load missing suites/tests
- [x] test load errors
- [ ] test running errors

When using the Visual Studio Code Remote Extension for WSL, the Test Explorer UI shows the "Error while loading tests - click to show" error message as the test suite and is unable to load and run any tests. The error message in the terminal reads: `[32m'/bin/sh: 1: jest: not found\n'[39m`

Loading the same project directly on Windows or macOS works without any issues.

**To Reproduce**
1. Clone [this example repository](https://github.com/peterjuras/vscode-jest-test-adapter-wsl-issue) in a wsl folder (e.g. ~/)
2. Open Visual Studio Code from WSL to activate the remote extension: `cmd.exe .`
3. The Test Explorer UI shows the error

**Expected behavior**
The error should not be shown an the tests should be loaded and displayed just as under native Windows or macOS.

**Screenshots**
[Screenshot](https://imgur.com/T7Vn9Nx)

**Link to source**
[Example repository to reproduce the issue](https://github.com/peterjuras/vscode-jest-test-adapter-wsl-issue)

**Desktop (please complete the following information):**
 - OS: Windows 10 | WSL 2.0
 - Default WSL shell: zsh

**Comment by rossknudsen** [comment]
Interesting, I'm having trouble reproducing the issue.  I initially had a problem, in Windows but all attempts in recreating the problem in WSL have been unsuccessful (thanks for the repo by the way).  I'm using Windows 10 with Ubuntu (not sure what the default shell is, but I assume bash).  I cloned to ~/vscode-jest-test-adapter-wsl-issue.

This is what it shows in my vscode editor regarding the extensions I have enabled in WSL:

![image](https://user-images.githubusercontent.com/2489915/82751315-6cc60600-9e0a-11ea-8f0e-27a7da2f3afb.png)

**Comment by peterjuras** [comment]
Thanks for the quick response and the screenshot. It appears that the issue was that my WSL version of jest test explorer was still 0.4.0, since 0.5.0 is not released yet in the extension store (or at least I don't see it).

Manually updating/installing the 0.5.0 version in WSL fixed this for me.

**Comment by rossknudsen** [comment]
Awesome, glad to hear that worked for you.  This issue is tracked by #34, but I wasn't aware it was preventing updates from occurring.
