### ISSUE TITLE
Replace parsed tests with tests discovered at runtime

### ISSUE THREAD

**Issue by rossknudsen** [kavod-io/vscode-jest-test-adapter#69]
When tests are discovered at runtime, we should remove any parsed tests for that file. This is because the parser sometimes gets the names of tests incorrect and then they don't match the runtime tests. 

Also consider handling duplicate named tests.

**Comment by RA80533** [comment]
I just encountered this anomaly with my project. Some of my tests are named after runtime-defined values (e.g., `f.name` where `f` is the name of the function being tested). The UI displays empty items for each test named in such a manner until the test suite is run after which the list is populated with duplicate tests with the correct names.

**Comment by rossknudsen** [comment]
Hi. Yes this is known behaviour. Basically the parser that is reading your test files thinks it can understand the names of your tests - but it gets them wrong and then when runtime discovered tests are added you get the duplicates. I'm thinking that I should throw away the parsed test results after receiving the runtime ones.

The parser is a third party dependency that is about to have a major update which should improve the parsing.
