### ISSUE TITLE
No feed back when executing tests

### ISSUE THREAD

**Issue by ChamNouki** [kavod-io/vscode-jest-test-adapter#71]
**Describe the bug**
- [ ] test load missing suites/tests
- [ ] test load errors
- [x] test running errors

All of my tests are well discoverd and visible in the test explorer with a grey circle icon on lleft side.

When I try to run one or suites/describe there is only a bleu circle for seconds then nothing. No output at all, even going back to the grey icon in test explorer panel.

When i run test with debug, vscode debugger connect correctly to test runner and I see classical jest output inside vscode debug console. So tests are well executed. But breakpoints dosn't work.
On debug mode I could see the following warning at the top of the log : 
```Program path uses differently cased character as file on disk; this might result in breakpoints not being hit.```

I work on a regular vuejs project with Typescript. My `package.json` and `jest.config.js` files are in project root folder wich is my vscode workspace too.

the jest config :
```
module.exports = {
  preset: '@vue/cli-plugin-unit-jest/presets/typescript-and-babel',
  collectCoverageFrom: [
    '**/src/**/!(App.vue|main.ts|router.ts)',
    '!**/plugins/**/*.ts',
    '!**/*.json'
  ],
  testMatch: [
    '**/tests/unit/**/*.(spec|test).(js|jsx|ts|tsx)',
    '**/__tests__/*.(js|jsx|ts|tsx)'
  ],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    vuetify: '<rootDir>/node_modules/vuetify',
    '\\.(css|less)$': 'identity-obj-proxy'
  },
  automock: false,
  setupFiles: ['<rootDir>/tests/setup-jest.ts'],
  setupFilesAfterEnv: ['<rootDir>/tests/setup-tests.ts']
};
```

PS: I use jest test explorer on an other project without vuejs but with Typescript too and it seems to work very well (success, failure, breakpoints...). So it's possible that vuejs could be the "probleme". Any way I didn't find any log of failure from jest test explorer in the vuejs project.

**Desktop (please complete the following information):**
 - OS: OSX

**Comment by rossknudsen** [comment]
I believe that the issue you are experiencing is tied directly to the message that you posted:
> Program path uses differently cased character as file on disk; this might result in breakpoints not being hit.
Because the filenames of the tests that are discovered don't match up with what is reported back by Jest then you get the blue indicator and cannot hit the breakpoints.  This could be as simple as a casing issue or the use of accenting characters - I found a lot of different solutions on StackOverflow.

In the meantime, you could confirm that this is the issue by using [this extension](https://marketplace.visualstudio.com/items?itemName=firsttris.vscode-jest-runner) instead.  If you get the same behaviour when debugging, then you'll know that the problem lies in your codebase.

**Comment by ChamNouki** [comment]
Nop, with Jest Runner that I actually use (but I would much prefer to use yours), breakpoints works perfectly

**Comment by CEbbinghaus** [comment]
> Nop, with Jest Runner that I actually use (but I would much prefer to use yours), breakpoints works perfectly

This comment alerted me to the fact that there is a Jest runner separately from the Test Explorer (which now uses the unified VSCode test API) which is working just fine for me. Personally i would still prefer to continue using this plugin but the Jest runner seems to be working while this ones goes to blue and then fails.
