### ISSUE TITLE
Support yarn workspaces

### ISSUE THREAD

**Issue by FrozenKiwi** [kavod-io/vscode-jest-test-adapter#72]
**Describe the bug**
- [X] test load missing suites/tests
- [X] test load errors
- [X] test running errors

**To Reproduce**
1: Load workspace with jest installed at a non-root location.

"Error While Loading Tests"
```
[32m"'jest' is not recognized as an internal or external command,\r\n"[39m +
  [32m'operable program or batch file.\r\n'[39m
```

**Expected behavior**
Can find tests and run as normal

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, OSX]

**Additional context**
This is a known issue, but I didn't see anything logged for it so I thought I would start the convo here.

What's the estimated effort to get this running?  It sounds like this is something you've already looked at/planned for, I wouldn't mind putting in a bit of effort to get this going if you have a clear spec and can give me pointers to get started

**Comment by rossknudsen** [comment]
Thanks for raising this and if I understand you correctly you are interested in contributing.  I've not worked with Yarn workspaces before, which is why it is not implemented. 

You should be able to close the repo and run it in debug mode (you'll probably need to uninstall the store version). The thing you are interested in is the RepoParser folder. You'll need to implement a new one for Yarn WS.  Let me know if you need more direction, I'm replying on my phone so not super helpful.

**Comment by FrozenKiwi** [comment]
I'd like to do this properly (so please leave this open), but for now at least I have found a workaround:

In each workspace project, hoist 'jest' binary file by adding `jest: "*"` to package.json `devDependencies`

**Comment by rossknudsen** [comment]
Hey, I looked at your original message again in the light of your workaround. So if Jest is not included as a dependency, then this extension assumes it is installed globally (I'm not completely happy with this but haven't come up with a better solution). 

So if you didn't have Jest as a dependency and it couldn't be found globally, what executes your tests?

**Comment by RA80533** [comment]
I stumbled upon it working with my project. The extension seems to work if there is a jest.config.json file at the root workspace that defines child workspaces via the [`projects`](https://jestjs.io/docs/en/configuration#projects-arraystring--projectconfig) property like so:

```json
{
  "projects": [
    "lib/*"
  ]
}
```

Make sure Jest is either hoisted to the root from the child workspaces or separately added to the root workspace itself.

**Comment by FrozenKiwi** [comment]
Thanks for the tip @RA80533 - that's neat tip!

This issue was more about the "debug" codelens button not being able to find jest if it hasn't been hoisted.  Because the debug config expected jest to be present in node_modules it would fail if it was just installed once at the root of the system.  Unless I'm misunderstanding you?

I have a root jest config, but then I have individual ones for each project as well, where I import the root one and (usually) jest re-xport the defaults.  If you just use a root config, does jest function if you just limit it to a single project?  Could you mix the two setups?  I'm curious - I started with just a single config but thought I needed to create individual jest configs to get individual setups working.  Perhaps I missed something there.

**Comment by RA80533** [comment]
@FrozenKiwi 

Could you elaborate on what you consider a setup?

Before using vscode-jest-test-adapter, my typical monorepo structure was such that each non-root workspace using Jest contained a Jest configuration file in its project directory. For example, a few of my projects were structured similar to the following:

- \<root\>
  - lib
    - client
      - jest.config.json
      - package.json
    - server
      - jest.config.json
      - package.json
  - package.json

In such projects, client and server included Jest as a developer dependency in their package.json files. At the time, I did not configure Jest at the root directory simply because the amount of Jest configuration shared between client and server was quite small.

**Comment by FrozenKiwi** [comment]
Belatedly: @RA80533  but here is a quick description of my setup:

I have a lot of shared code.  I try to enforce similarity as much as possible.  My folder structure is similar to yours, but I try to only list *any* shared dependencies once at the root level (hoping that sharing as much as possible leads to the least chance of surprises when using code in different projects).

In my root I have `jest.config.js`, which has all shared configuration (including things like path remapping, and general setup).

For each leaf (lib/app) Jest expects a config at its root, so we give it one but most of them are very light:
```
const defaults = require('../../jest.config');

module.exports = {
  ...defaults
};
```

However, we can still overwrite any config settings if we need.

In each package.json, we need to include:
```
  "devDependencies": {
    "jest": "*",
    ...
  }
```

This basically says it expects jest to be here, but doesn't care what kind of jest.  So instead of a full install of jest (and a potentially project-specific set of issues etc), it just hoists the launcher into the local node_modules.

This is mostly due to our priorities, YMMV.  We write a lot of code that runs in a lot of different environments.  And I hate surprises :-)

**Comment by FrozenKiwi** [comment]
I'mma close this.  The workaround isn't perfect, but probably the best we'll manage for now.
