### ISSUE TITLE
testPathIgnorePatterns not respected 

### ISSUE THREAD

**Issue by MNorgren** [kavod-io/vscode-jest-test-adapter#75]
**Describe the bug**
- [x] test load missing suites/tests
- [ ] test load errors
- [ ] test running errors

My project structure is based upon @nrwls directory structure and I have one project nested within another. The parent's `jest.config.js` excludes the child directory by using the `testPathIgnorePatterns: ["/child/"]` and upon running `ng test parent`, I see that the child's tests are excluded (as expected).

**Issues:**

1. When viewing the tests in the test explorer, the child tests are duplicated in both the parent project, as well as the child project.
2. When running the child tests under the parent's directory nothing happens. When running in debug mode, it freezes and I cannot even kill the debug configuration
3. When clicking the 'Run' button from within the file, I am prompted with 2 options to run from (the parent and the child).

**To Reproduce**
1. Create the following directory structure
- \parent
  - \child
      - \src\
          - child-test.spec.ts
      - jest.config.js
  - \src
      - parent-test.spec.ts
  - jest.config.js

2. Inside the parent's jest.config.js, add the `testPathIgnorePatterns: ["/child/"]`
3. View test explorer and see duplicated tests
4. Click run from within the `child-test.spec.ts` and see the prompt for to choose which suite to run (parent, child or both)

**Expected behavior**
Expected that the child tests are excluded from the test explorer window and when clicking run from within the window, it knows that it is only a part of a single jest configuration

**Screenshots**

![image](https://user-images.githubusercontent.com/3640233/88190840-62549c80-cc00-11ea-9a2d-1d3c5f73cfd4.png)

![image](https://user-images.githubusercontent.com/3640233/88190903-76989980-cc00-11ea-8351-9d8eb026709f.png)

![image](https://user-images.githubusercontent.com/3640233/88191227-d131f580-cc00-11ea-8515-397d2c9ca099.png)

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
Angular project, built using nrwl

**Comment by rossknudsen** [comment]
Can you try enabling the feature toggle "UseNxCli"?  You should find that node under extension settings.

**Comment by MNorgren** [comment]
Thanks for the quick reply. I am excited to get using this test adapter! I believe I have enabled the featureToggle appropriately, according to how the code reads. Let me know if I have it incorrectly configured:
![image](https://user-images.githubusercontent.com/3640233/88292626-80350680-ccbf-11ea-8af1-2f7110160cd0.png)

I've restarted VSCode since enabling and I am still seeing the tests duplicated in the Test Explorer window as well as in the editor's 'Run' prompt.

**Comment by rossknudsen** [comment]
Yes, you have done that correctly.  It may be that it doesn't sole the issue you are experiencing.  The other thing that you need to do is, make sure that you are using a version of Nx > 9.2.4.  I submitted a PR to make it possible to use the 'nx' command to retrieve the jest settings.

**Comment by rossknudsen** [comment]
Can you try running `nx test <project name> --showConfig` for the relevant projects?  In particular look for any configurations that use the `testPathIgnorePatterns` setting.  I'm guessing that is how `nx` excludes the child project from the Jest test run.

If that is the case, I'm only using the `testRegex` to find tests.

**Comment by rossknudsen** [comment]
Ugh, I read your original post again. You pretty clearly note that you've set `testIgnorePatterns` in your project.  Looks like I need to add that functionality in.

**Comment by rossknudsen** [comment]
@MNorgren were you interested in raising a PR to implement this?  I can point you to the location of code that needs to change.  It would be slightly complex only in that you have to handle the possible values that `testIgnorePatterns` can take on (e.g. `<rootDir>\...`).

**Comment by rossknudsen** [comment]
Actually, I've just implemented - it wasn't too hard.  But can you try uninstalling the marketplace version of this extension and try installing the build I ran for this fix?  You can install it from here:

https://dev.azure.com/kavod-io/vscode-jest-test-adapter/_build/results?buildId=78&view=artifacts&type=publishedArtifacts

If you are satisfied that it works, then I'll merge it into release 0.6.1.
