### ISSUE TITLE
Add a display option that disregards file structure

### ISSUE THREAD

**Issue by tomprogers** [kavod-io/vscode-jest-test-adapter#79]
We we run jest from the command line, it displays the tests as they are logically structured, not as they are distributed on disk. I wish JTE had a display option similar to that.

I don't want to see a tree that reflects file organization. I want to see a tree composed of `describe` and `it`/`test` blocks, without any visual indication of the file structure.

**Comment by dannymcgee** [comment]
Came here to say the same thing. I'm looking at the code now and it seems like a pretty straightforward thing to add, so I'll try to get a PR up shortly.

**Comment by rossknudsen** [comment]
Hi @tomprogers / @dannymcgee,

Question for you both: can you look at the following page on the host extension site and tell me if it meets your needs?

https://github.com/hbenl/vscode-test-explorer

The setting `testExplorer.mergeSuites`

**Comment by dannymcgee** [comment]
@rossknudsen Unfortunately not for me. I do have that option enabled and I can see why it's useful, but the pain point I'm trying to address is that my test files are all pretty deeply nested inside my workspace directory structure, so I need to expand 5 or 6 nodes in the UI to see my first actual test suite, which leads to a lot of wasted horizontal space in the sidebar and a lot of clicking to see anything. If you take a look at the [screenshots in my PR](https://github.com/kavod-io/vscode-jest-test-adapter/pull/80), the issue I'm having should be more clear.

**Comment by rossknudsen** [comment]
nah, that's fine.  I just thought I'd check before merging.  I'll have another look later on, but the initial review looked good.

**Comment by tomprogers** [comment]
Heya! Thanks for following up.

I think I'm with danny on this. I do use the `mergeSuites` setting, but it's still not enough. As an example, I'm working on an Electron app, which adds another layer of folders to accommodate the main and renderer threads. By the time an actual `describe` appears, it's already indented like 4 levels. When I run jest, I don't see any of that wrapping FS structure.
