### ISSUE TITLE
Parameterized testing (theories) do not discover or run in Test Explorer

### ISSUE THREAD

**Issue by AArnott** [kavod-io/vscode-jest-test-adapter#84]
**Things to consider before raising a bug**
This extension needs to understand how your project(s) are structured, where to find your test configuration and test files among other things.  It turns out that there are many ways to structure JS projects and the extension may not currently accommodate your project.  The following section is to aid in collecting information to identify the issue.

**Describe the bug**
- [x] test load missing suites/tests
- [x] test load errors
- [x] test running errors

**To Reproduce**

Define tests in a parameterized way, such as:

```ts
[1, 2, 3].forEach(protocolMajorVersion => {
    describe(`MultiplexingStream v${protocolMajorVersion} `, () => {
        it('should work ', () => { });
    });
});
```

You can see below how the test discovery considers the strings passed to the test APIs as literals instead of allowing them to execute and use the interpolated strings. This prevents them from running at all. 

![image](https://user-images.githubusercontent.com/3548/93489365-aa243700-f8c4-11ea-81c0-1adba3420496.png)

**Expected behavior**

Like the Jasmine test extension, I expect the parameterized tests to be individually identified and runnable.
![image](https://user-images.githubusercontent.com/3548/93489036-4732a000-f8c4-11ea-88ba-bdee7f11ba49.png)

**Link to source**

```
git clone https://github.com/AArnott/Nerdbank.Streams.git
cd Nerdbank.Streams/src/nerdbank-streams
git checkout vscode-jest-test-adapter#84
yarn
code .
```

Alternatively if you check out 4e1dfcbbceba56dfbb5c12910437f2d0bd60ebb2 you can see how jasmine works. But you'll have to  run `yarn` and `yarn tsc`, and reload VS Code for the tests to show up. 

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**

I would like to switch from jasmine to jest because jest allows running tests directly from typescript instead of having to compile to .js first. But in this particular repo where I use parameterized tests, this is an adoption blocker.

**Comment by rossknudsen** [comment]
Yes, this is a known issue and I'm working on a fix for it as part of #69.  Originally these tests were not displayed at all, but they were added in #68 with the above ticket raised to improve the display of them.

With the code you have (describe block in a for each loop) the only way to determine how many tests and their names is to execute the code.  The Jest extension only executes the tests when you run them, if you just refresh the listed tests, it will use a parser to find the names of the tests.  Its not clear from your screenshot whether you have executed the tests or not.  However, you will still not get the result that you want at the moment.  #69 will greatly improve the UX however.

**Comment by AArnott** [comment]
>  Its not clear from your screenshot whether you have executed the tests or not. 

I have tried. I execute all of them but the ones that haven't run in that screenshot didn't run as part of the batch. If I click to run them specifically, they similarly never run. 

It sounds like #69 will indeed work. I'm fine with having to run the tests once before the parameterization expands.

**Comment by rossknudsen** [comment]
I had a go at running your test sample with the latest 0.7.4 version:

This is what I get on initial load of the tests:
![image](https://user-images.githubusercontent.com/2489915/93654039-b1d40f00-fa6f-11ea-977f-03079a7a884a.png)

and after running the tests:
![image](https://user-images.githubusercontent.com/2489915/93654045-b8628680-fa6f-11ea-9039-8c6e4c7b54f4.png)

So after the tests are run, you get the right tests showing up, just intermixed with the originally discovered tests which are broken.  So if you can imagine what it will look like when the original tests that do not have a green tick next to them disappear, then you will end up with something like this:
![image](https://user-images.githubusercontent.com/2489915/93654154-3faffa00-fa70-11ea-96f0-55c6c49704be.png)

So you should get the desired effect once #69 has been completed when you run the tests.  Unfortunately when the tests are discovered (either at initial load or when you hit the refresh icon in the test explorer) the test files are _parsed_.  The parser is only so good and obviously at some point the only way to determine the correct number and names of tests/describes is to execute the file.  I'd like to in the future introduce a "parser" that actually executes the test file, but doesn't actually run the bodies of the tests themselves.  But there are a lot of gotchas in that regard as you need to mock and run all the before*/after* methods etc to get the true effect.  Also some people may have side effects from this that they do not want.  So there is quite a bit of work to do there.

**Comment by AArnott** [comment]
Wow. The jasmine test discovery I assumed simply executes the js file without executing the `it` delegates. I hadn't thought about the before/after methods, but skipping those delegates seems reasonable for most cases as WELL, IMO.

**Comment by TheSench** [comment]
The duplicates are caused by a bug in the `vscode-test-explorer` extension ((issue #177)[https://github.com/hbenl/vscode-test-explorer/pull/177]).  I have a PR up to clean those up, so hopefully that will go away.

As far as actually being able to run the tests, the way the Jest runner works is that it takes in a regex expression to determine what tests to execute.  We could replace placeholders with regex that would match the possible test names without knowing the values passed in.  For Jest's `it.each(array)` syntax, we can make the regex fairly smart, as it uses ["printf formatting"](https://jestjs.io/docs/en/api#1-testeachtablename-fn-timeout), which limits the possible values it would replace placeholders with.

**Comment by TheSench** [comment]
Duplicates should be gone when the next `vscode-test-explorer` version goes out.  [Issue #177](https://github.com/hbenl/vscode-test-explorer/issues/177) is now closed.
