### ISSUE TITLE
Losing log's from logging libraries (bunyan, winston)

### ISSUE THREAD

**Issue by FrozenKiwi** [kavod-io/vscode-jest-test-adapter#87]
I'm using bunyan, but I believe this extends to winston too: https://github.com/microsoft/vscode/issues/19750

**Describe the bug**

Logs info is not written to internal console when debugging tests.  (Including try/catch info, and exceptions from inside jest itself).

**To Reproduce**

Setup logging with bunyan:
```
  log = bunyan.createLogger({
    name,
    streams: [
        getConsoleStream()
      ]
  });
```
Using a logging library with stdout logging: try:
```
it('Succesfully Processes Actions', async ()=> {
  console.log("see me?", { var: "hello"});
  process.stdout.write("hellow?");
  log.trace('tracing');
  log.debug('debugging');
  throw new Error("this is important");
});
```

**Expected behavior**
We need logging to work when debugging.  Losing exception info is

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, OSX]

**Workaround**

Suggestion from the linked issue: Switching to`console` to  `intergratedTerminal` prints the output there correctly (option in preferences for this extension).

**Fix**

The way to fix this (again from linked issue) is to capture stdout 
```
outputCapture: "std", 
```
on debug configuration. Not everyone will want this though, only users of logging libraries will benefit.  Could we add this is an option?  I've never done any extension development for VSCode, but if you give me some pointers on how to add the option I can figure the rest out and submit a PR.

**Comment by rossknudsen** [comment]
Cool, it seems that you've all but solved the issue, so I may as well point you in the right direction and you can raise it as a PR.  You should be able to clone this repo and press F5 to run the extension in debug mode (opens a new instance of code).  You'll probably want to uninstall the marketplace version of this extension first.  The area you want to change is [here](https://github.com/kavod-io/vscode-jest-test-adapter/blob/master/src/adapter.ts#L160-L172).

Let me know if you need any more assistance.

**Comment by rossknudsen** [comment]
@FrozenKiwi can you see if v0.8.0 covers your needs?  Test output is now written to an Output Window in VSCode.  If this doesn't include some of the logging output, then we may need to look at it further, but it should have any console.log calls etc.  I'll close this for now, but if you find that there is ongoing issues, please feel free to reopen.
