### ISSUE TITLE
Multiple Jest configs in workspace

### ISSUE THREAD

**Issue by rossknudsen** [kavod-io/vscode-jest-test-adapter#9]

**Comment by calebboyd** [comment]
Prior art: The eslint plugin supports `"workingDirectories": [{ "mode": "auto" }]` https://github.com/microsoft/vscode-eslint#settings-options which just assumes a configuration per package.json

**Comment by rossknudsen** [comment]
This issue kind of has a couple of aspects.  The first is when there is actually multiple projects in the same repository - a monorepo.  Which is straight-forward, each kind of monorepo needs some way to identify themselves and their configuration.  Some monorepo support is in place.

The other thing is when there are more than one jest config present because they are used for different purposes.  One project I work on has a config for build, test and a separate common config between the two.  I need some way to figure out which one to use.  I haven't really got a good solution for that yet, but it ties in with a number of other configuration problems that I have to solve.
