### ISSUE TITLE
Need to provide command line options to Node when running  a test

### ISSUE THREAD

**Issue by jodre11AtTRT** [kavod-io/vscode-jest-test-adapter#93]
In my `package.json`

```
"scripts": {
    "test": "npx --node-arg=--experimental-vm-modules jest"
  }
```

I pass the `--experimental-vm-modules` option to node when launching `jest`.

When I run the tests from the VSCode Test Runner, this option is not passed. Consequently, I get the output

> SyntaxError: Cannot use import statement outside a module
> 
>       at Runtime._execModule (node_modules/jest-runtime/build/index.js:1179:56)

The tests do not run.

I need this because I want my tests and my targets to be in ES6 modules.

**Comment by jodre11AtTRT** [comment]
Looks like the run problem might be imported from `jest-editor-support` however,
for debug, the path to jest seems to be hardcoded.

**Comment by rossknudsen** [comment]
Yes the debug config should be more dynamic using some of the functions that the run step uses. You're welcome to raise a PR if you want. 

At the moment I'm waiting for another PR to be merged into `jest-community/vscode-jest` which will probably deprecate a lot of that code anyway.

**Comment by rossknudsen** [comment]
Note that you might be able to configure the jest command setting to `npm run test` to override the run step.

**Comment by charles-allen** [comment]
I believe that #135 would also solve this (if 135 is possible)

**Comment by rickstaa** [comment]
@rossknudsen So `node --experimental-VM-modules node_modules/jest/bin/jest.js` in `jestTestExplorer.pathToJest` would work? I enabled logging, but it doesn't show the executed command. It would be amazing if `env` variables are supported in the future 🚀.

**Comment by rickstaa** [comment]
@rossknudsen I tested your solution and setting `jestTestExplorer.pathToJest` to `node --experimental-vm-modules node_modules/jest/bin/jest.js` in settings.json solves my problems. 🚀

**Comment by rickstaa** [comment]
The only thing I can not get to work is the debug breakpoints. @rossknudsen Do you know a way to make the debugger work?

#### Steps to reproduce

1. Clone [this example](https://github.com/rickstaa/es6-jest-example) repository.
2. Add `"jestTestExplorer.pathToJest": "node --experimental-vm-modules node_modules/jest/bin/jest.js"` to your `settings.json` file.
3. See that the tests show up in the test adapter.
4. See that you can run the tests using the adapter.
5. Set a breakpoint.
6. Try to debug a test.
7. See that the debugger does not stop at the breakpoints.

**Comment by seanfuture** [comment]
One thing to try @rickstaa that's worked for me in the past is to ensure the following configuration is present in your `launch.json`:

```
{
    "type": "node",
    "name": "vscode-jest-tests",
    "request": "launch",
    "program": "${workspaceFolder}/node_modules/jest/bin/jest",
    "args": [
        "--runInBand"
    ],
    "env": {
        "NODE_OPTIONS": "--experimental-vm-modules"
    },
    "cwd": "${workspaceFolder}",
    "console": "integratedTerminal",
    "internalConsoleOptions": "neverOpen",
    "disableOptimisticBPs": true
},
```

Recommend giving that a try when you can.  I'm able to debug jest w/o the annoying babel wrapper presently.  GL

**Comment by rickstaa** [comment]
@seanfuture Great, thanks a lot for your answer! 🔥

**Comment by Norlandz** [comment]
> @rossknudsen I tested your solution and setting `jestTestExplorer.pathToJest` to `node --experimental-vm-modules node_modules/jest/bin/jest.js` in settings.json solves my problems. 🚀

I tried, and the Output shows an Error
```
"'G:\\Microsoft' is not recognized as an internal or external command,\r\n" +
  'operable program or batch file.\r\n'
```

My vscode is in `G:\Microsoft VS Code\Code.exe`.

Not sure why the path parsing became wrong.
