### ISSUE TITLE
Clicking 'Run' on a suite or single test does nothing

### ISSUE THREAD

**Issue by zacaj** [kavod-io/vscode-jest-test-adapter#94]
**Describe the bug**
- [ ] test load missing suites/tests
- [ ] test load errors
- [x] test running errors

Test Explorer lists all my tests correctly.  I can debug any test normally.  When I click the run button (in the explorer or in my code), nothing happens at all.  I enabled the Logpanel setting, and I get this output:

    [2020-10-03 16:33:51.905] [INFO] Running Jest tests... ["undefined▪a:\\source\\project\\test.spec.ts♦name"]
    [2020-10-03 16:33:51.905] [INFO] Finished loading Jest tests.

When I click 'Run All' for the entire project, it works fine (a Blue 'play' icon appears, then a while later it changes to a green check, although I don't see any log output during this process?).  

I assume that 'undefined' shouldn't be there in the path?  I tried setting the 'Path to Jest' setting (although it's unclear exactly what it should be set to, or how to tell when the auto detection has failed) to "${rootPath}\node_modules\.bin\jest", but that had no effect on the 'undefined' in the logs.

My project is typescript based, using jest + ts-jest.  jest.config.js is at the root of the workspace, along with the node_modules folder where jest is installed.

**Desktop (please complete the following information):**
 - OS: Windows 10 x64

**Comment by rossknudsen** [comment]
Can you have a look at v0.7.5, just released to marketplace?  @TheSench has contributed which may fix this issue.
