### ISSUE TITLE
Unable to run Typescript based tests

### ISSUE THREAD

**Issue by carlba** [kavod-io/vscode-jest-test-adapter#97]
My tests are in Typescript and when I execute them I get 

```bash
Could not read source map for file:///Users/cbackstrom/development/robot-assignment/node_modules/typescript/lib/typescript.js: ENOENT: no such file or directory, open '/Users/cbackstrom/development/robot-assignment/node_modules/typescript/lib/typescript.js.map'
```

When I execute the same command line that is executed by the extension in the terminal everything works.

**Comment by cefn** [comment]
I also encounter this issue. When running with the inline `Debug` control next above the test provided by [Jest Runner](https://marketplace.visualstudio.com/items?itemName=firsttris.vscode-jest-runner) it correctly launches a debug session.

Jest Runner seems to launch within a console in the **_Terminal_** panel called `Node Debug Console` while Test Explorer seems to launch (and fail) within the **_Debug Console_** panel itself.

Contrast the following screenshots of Test Explorer Failing...

![image](https://user-images.githubusercontent.com/159819/103341115-daf83880-4a7d-11eb-9545-20e66521b9b3.png)

...and Jest Runner succeeding.

![image](https://user-images.githubusercontent.com/159819/103341169-09761380-4a7e-11eb-8ec1-3bc85962fc94.png)

**Comment by kinnrot** [comment]
I guess if it could just integrate with the existing Run|Debug configuration from jest/jest runner it would make things simpler

**Comment by rossknudsen** [comment]
I tried a PR to do that, but they weren't keen at the moment.

**Comment by elsassph** [comment]
On Mac, with `jest` configured to use `ts-jest` as transformer, I get an obvious TS-being-parsed-as-JS error:
```
[SyntaxError: Unexpected token, expected "}" (95:17)
```

**Comment by skamansam** [comment]
I'm running vue tests with jest, and when I try to debug a test, i get a similar error with `buble-browser-deps.js.map`. The tests run fine, but the debugger fails with this error. All the other Jest test runners i tried work well with tests and debugging, so I know it must be something wrong with this extension.
