### ISSUE TITLE
Explorer cannot find tests

### ISSUE THREAD

**Issue by rahuldixit** [kavod-io/vscode-jest-test-adapter#98]
**To Reproduce**
1. Install Jest Test Explrer
2. Got explorer window and refresh
3. No tests are visible

**Expected behavior**
We expect to see tests

**Additional context**
The tests are typescript ....test.ts files. Is there config to specify path to test files (glob pattern), and the fact they are typescript files?

**Comment by jarrettmeyer** [comment]
Same problem here. This is a big monorepo project (probably too big). Tests are not stored in root, and this is a typescript project.

```
my-project/
    auth-functions/
        server-auth-node/
            src/
            tests/
            package.json
```

**Comment by KaiRoesner** [comment]
In the ["Getting started"](https://github.com/kavod-io/vscode-jest-test-adapter#getting-started) section of their homepage, they say
> Currently limited to Jest being available from the ./node_modules/.bin/jest path from the VS Code workspace directory. We are working to make this more flexible.
This is probably the reason why tests are not found in a monorepo folder structure.

**Comment by benruehl** [comment]
Same here. The test explorer is just empty. Even after restarting VS Code. Our project is rather small, tests are written in Typescript and the path `./node_modules/.bin/jest` exists.

**Comment by rossknudsen** [comment]
> Same problem here. This is a big monorepo project (probably too big). Tests are not stored in root, and this is a typescript project.
> 
> ```
> my-project/
>     auth-functions/
>         server-auth-node/
>             src/
>             tests/
>             package.json
> ```

As a debugging step, can you try opening VSCode in the following folder:

> ```
> my-project/
>     auth-functions/
>         server-auth-node/
> ```

I.e. open the folder so that `package.json` is at the root.  The extension has to make sense of the structure of your souce and it won't currently recognise that structure.

**Comment by AlbertoBonfiglio** [comment]
I can confirm the issue is the node_modules not being in the root folder. I have a .net project with an api and a subfolder hosting the angular client. I f I open the workspace containing both I get no tests found. If I open the client app folder directly in vs studio I get all the tests. 
I woudn't mind collaborating to find a way to fix the issue.
What would make more sense? A specific string path in the configuration or to allow the extension to recurse through the workspace and find a node_modules/.bin/jest folder by itself?

**Comment by rossknudsen** [comment]
I've discovered that there are a lot of variations on project structures in maintaining this extension.  More than can realistically be handled internally (without a lot of custom code and dealing with edge cases as they arise).  My thoughts on this are to allow users to provide the configuration needed to make sense of their project structure.  If you take a look at [this file](https://github.com/kavod-io/vscode-jest-test-adapter/blob/master/src/repo/index.ts), you'll see how there are a number of built in `RepoParser`s that provide an interface that the extension uses to discover and run the tests.  What I'd like is for another `RepoParser` that can read a JSON file (or ultimately execute a JS script) that would provide this information.  Ultimately the JSON/JS file would need to provide an array of `ProjectConfig`s.

The only hesitation on doing this, is that I'm not completely happy with the `ProjectConfig` interface for other reasons, but there is probably no good reason why the above feature can't be implemented now.  If anyone in this thread wants to have a go at implementing (or even discussing a design) feel free to contribute.  This feature would close a bunch of open issues, so is of reasonable value.

I'm not sure whether the config should be part of the VS Code config file, or should be in a separate file e.g. `.jest-test-adapterrc` / `jest-test-adapter.config.js` etc.  But maybe just start with a static configuration and as a separate effort look at the ability to execute a script file to generate a dynamic config.

**Comment by wSedlacek** [comment]
Came across a bug today with the Nx repo parser.

https://github.com/kavod-io/vscode-jest-test-adapter/blob/edf9c9af07998e726f641edfa23591fe97ed1e08/src/repo/NxdevAngular.ts#L31

`builder` can also be `executor`
`architect` can also be `targets`
`test` can be any arbitrary string.

This is a valid nx configuration.
```
{
  "version": 2,
  "projects": {
    "web-client": {
      "projectType": "application",
      "root": "apps/web-client",
      "sourceRoot": "apps/web-client/src",
      "prefix": "web-client",
      "targets": {
        "does-it-work": {
          "executor": "@nrwl/jest:jest",
          "outputs": ["coverage/apps/web-client"],
          "options": {
            "jestConfig": "apps/web-client/jest.config.js",
            "passWithNoTests": true
          }
        }
      }
    },
  },
}
```

Maybe there is an Angular or Nx API that can help with navigating the workspace configuration?

**Comment by wSedlacek** [comment]
After some more experence working with NX I have found that `FsTree` could be used to get the correct executor.
```ts
import { getProjects } from '@nrwl/devkit';
import { FsTree } from '@nrwl/tao/src/shared/tree';

const findWorkspaceRoot = (dir: string = process.cwd()): string => {
  if (dirname(dir) === dir) {
    throw new Error(`The cwd isn't part of an Nx workspace`);
  }

  if (existsSync(join(dir, 'angular.json')) || existsSync(join(dir, 'workspace.json'))) {
    return dir;
  }

  return findWorkspaceRoot(dirname(dir));
}

const tree = new FsTree(root, false);
const projects = getProjects(tree);
```

`projects` is then normalized to the nx interface regardless of if `executor` or `builder` is used.
Additionally this works with the new standalone configurations from nx.

**Comment by OzzyTheGiant** [comment]
I tried to just manually override the Path To Jest setting to use `${workspaceFolder}/node_modules/.bin/jest` and instead of not showing anything, the UI errors out and it said this in the console:

```
'/bin/sh: 1: ../../../node_modules/.bin/jest: not found\n'
```

I don't even...

**Comment by nonameolsson** [comment]
> 



> After some more experence working with NX I have found that `FsTree` could be used to get the correct executor.
> 
> ```ts
> import { getProjects } from '@nrwl/devkit';
> import { FsTree } from '@nrwl/tao/src/shared/tree';
> 
> const findWorkspaceRoot = (dir: string = process.cwd()): string => {
>   if (dirname(dir) === dir) {
>     throw new Error(`The cwd isn't part of an Nx workspace`);
>   }
> 
>   if (existsSync(join(dir, 'angular.json')) || existsSync(join(dir, 'workspace.json'))) {
>     return dir;
>   }
> 
>   return findWorkspaceRoot(dirname(dir));
> }
> 
> const root = findWorkspaceRoot();
> const tree = new FsTree(root, false);
> const projects = getProjects(tree);
> ```
> 
> `projects` is then normalized to the nx interface regardless of if `executor` or `builder` is used. Additionally this works with the new standalone configurations from nx.

Interesting! Mind helping where, and how, to configure NX to use this?

**Comment by angelfraga** [comment]
I also faced that. In my case, it also appears on `nx` workspace. 

Angular `nx` workspaces could contain either `angular.json` or `workspace.json`. 
Even it could be a `nx`  workspace with react & angular together. 

In my case,  the angular `NxdevAngular.ts` is not being taken in the count since  `angular.json` does not exist.
Instead, the `NxdevReact.ts` is chosen. I guess that only happens because the matching is done by checking if the file exists.

But I think we might want to open at least a new issue for `nx` workspaces to solve `nx` related issues.

**Comment by mbeckenbach** [comment]
Hey guys, 

current version of nx neither has the workspace nor the angular.json. 
Instead they use nx.json and project.json per project.

But they have a nice helper to get confgurations: 
import { readWorkspaceConfig } from 'nx/src/project-graph/file-utils';
